### PR TITLE
Temporary fix for #189

### PR DESCRIPTION
**Pull request by shmuelsash**
Change .mnemonics to `center`

### CODE REVIEW

**Comment by AnKingMed** [comment]
Do we need to push this asap?

**Comment by shmuelsash** [comment]
Ideally 

So Ahmed can accept the updates in the queue without it causing any issues for users

**Comment by AnKingMed** [comment]
@abdnh if you have time to look into https://github.com/AnKing-VIP/AnKing-Note-Types/issues/189 soon we can just address this issue. If not, can you merge this and push an update?

Thank you!

**Comment by abdnh** [comment]
This doesn't seem to fix the issue for me. Have you tested it @shmuelsash?

Adding `min-width: 50%;` appears to fix it.

**Comment by shmuelsash** [comment]
@abdnh changing .mnemonics to `center` doesn't take away the left justification for you?

**Comment by abdnh** [comment]
It does.

**Comment by shmuelsash** [comment]
So which issue isn't it fixing?

**Comment by AnKingMed** [comment]
@abdnh sounds like maybe we can push this now while we're looking into other solutions as long as it works for @shmuelsash

**Pull request merged**
