### PR TITLE
Support selective one-by-one clozes

### PR DESCRIPTION
**Pull request by abdnh**
https://community.ankihub.net/t/make-1-by-1-apply-to-specific-clozes/230261

## TODO:

- [ ] docs

### CODE REVIEW

**Comment by AnKingMed** [comment]
Can we add this to the one by one field description? 

> Type anything here (i.e. "yes") to enable one by one clozes or enable only certain clozes by typing numbers separated by commas (i.e. "1,3")

We can also add docs to the main ReadMe explaining this. Thanks! Looks like it will be cool!

**Comment by AnKingMed** [comment]
This doesn't seem to be working for me. 

I get the green color, but not the crowns doing the one by one anymore. I'm testing on "AnKing" note type

image

**Comment by abdnh** [comment]
What are these options set to?

image

Also what's the content of the one by one field?

Note that if selective one by one is enabled, the content of field will be interpreted as the cloze numbers where one by one should be enabled.

**Comment by AnKingMed** [comment]
I didn't realize I needed the add-on too. I updated my addon and now it's working, however if I select to do selective one-by-one, it no longer works if there's a "y" in there.  Can we make it so if there's a number, then interpret as selective one-by-one, but if anything else, just treat as a regular one-by-one (if that box is checked).

Also, I would set this as the default
image

**Comment by AnKingMed** [comment]
Working well for me! We can go ahead and push this update!

**Comment by abdnh** [comment]
Just pushed the update.

**Pull request merged**
